[project]
name = "distil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ishitarastogi", email = "ishita3099@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "feedparser>=6.0.14",
    "google-api-python-client>=2.198.0",
    "openai>=2.53.0",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.51",
    "youtube-transcript-api>=1.2.4",
]

[project.scripts]
distil = "distil:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
